---
- name: Remove WebP package
  become: yes
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - webp
    - libwebp-dev

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libgif-dev

- name: Is webp already installed?
  become: yes
  stat:
    path: "{{ webp_install_dest }}/bin/cwebp"
  register: webp_cmd
  changed_when: not webp_cmd.stat.exists

- block:
  - name: install build packages
    become: yes
    apt:
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - build-essential

  - name: Download WebP tarball
    become: yes
    unarchive:
      src: "{{ webp_download_url }}"
      dest: "{{ webp_download_dest }}"
      remote_src: true

  - name: Install WebP
    become: yes
    shell:
      "{{ item }}"
    args:
      chdir: "{{ webp_download_dest }}/{{ webp_dirname }}"
    with_items:
      - ./configure
      - make
      - make install
      - "ldconfig {{ webp_prefix }}/lib"
  when: not webp_cmd.stat.exists
